onejar: PackageVersionedZip
main: org.litesoft.packageversionedzip.PackageVersionedZip

dependencies:
- 3rdPartyCode/TarReader
- ../PackagedVersionCommon

classpath:
- 3rdPartyCode|**.jar
- ../LiteSoftServerUtils/libs|**.jar

resources: 
- LICENSE

